name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run analyze.py
        run: python analyze.py

      - name: List output directory contents
        run: ls -al output/
        
      - name: Check output directory size
        run: du -sh output/
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: output
          path: output/
          retention-days: 30
      
      - name: Push the new files to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output